
  CREATE TABLE "KOOKHWA"."ORACLE_TABLE" 
   (	"HSTR_SEQNO" NUMBER(10,0) NOT NULL ENABLE, 
	"TX_DTTM" VARCHAR2(16 BYTE) NOT NULL ENABLE, 
	"CUST_CENR_SRVC_TYCD" VARCHAR2(2 BYTE), 
	"CUST_CENR_PROG_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PROG_NM" VARCHAR2(50 BYTE), 
	"SRVC_TX_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"SRVC_TX_NM" VARCHAR2(300 BYTE) NOT NULL ENABLE, 
	"CSTNO" VARCHAR2(16 BYTE), 
	"DATA_CTNT" VARCHAR2(4000 BYTE), 
	"USER_IPAD" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "ORACLE_TABLE_PK" PRIMARY KEY ("HSTR_SEQNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
